import fs from 'fs-extra';
import path from 'path';
import { execa } from 'execa';
import { loadConfig } from '../lib/config.js';
import { isClaudeAvailable, runAiPrompt } from '../lib/ai.js';
import { print } from '../lib/output.js';
import { parseDiffToMetadata, countMembers } from '../lib/metadata-mapper.js';

const VALID_FORMATS = ['github', 'slack', 'markdown'];

const GITHUB_PROMPT = `You are generating a professional pull request description for a Salesforce DX change. Produce concise GitHub-flavored markdown with these sections:

## Summary
One paragraph (2-4 sentences) describing what the change does and why. Focus on business impact, not the mechanics of individual commits.

## Metadata Changes
A bulleted list grouped by metadata type, using the component breakdown provided. Keep it scannable — do not copy the raw lists verbatim when they are large.

## Test Plan
A checklist (- [ ]) of concrete verification steps someone reviewing or deploying this PR should perform.

## Rollback
One line describing how to roll back if the deployment fails.

Rules:
- Do not invent ticket numbers, author names, or URLs.
- Do not include a "Generated by AI" footer.
- Keep the whole response under ~400 words.

`;

const SLACK_PROMPT = `You are generating a Slack announcement for a Salesforce deployment. Produce Slack mrkdwn (NOT GitHub markdown — use *bold* not **bold**). Structure:

:rocket: *<branch or version>* is ready for deploy

*Summary*
1-2 sentence description of the change.

*What's changing*
- 3 to 5 bullets covering the biggest components or behaviors touched

*Reviewers*
_(leave this line as a placeholder for the caller to fill in)_

Rules:
- Keep the whole message under 180 words.
- Use Slack emoji shortcodes (:white_check_mark:, :warning:) where helpful.
- Do not invent metrics or coverage numbers that are not in the provided context.

`;

export function registerPrDescriptionCommand(program) {
  program
    .command('pr-description')
    .alias('pr-desc')
    .description('Generate a PR description or Slack message from deployment changes')
    .option('--base <ref>', 'Base branch to diff against', 'main')
    .option('--head <ref>', 'Head ref', 'HEAD')
    .option('--format <fmt>', `Output format: ${VALID_FORMATS.join('|')}`, 'github')
    .option('--output <path>', 'Write result to this file instead of stdout')
    .option('--commit-limit <n>', 'Max commits to include in the context sent to AI', '30')
    .action(async (options) => {
      try {
        if (!VALID_FORMATS.includes(options.format)) {
          print.error(
            `Unknown format "${options.format}". Valid: ${VALID_FORMATS.join(', ')}`,
          );
          process.exitCode = 1;
          return;
        }

        const config = await loadConfig();
        const projectRoot = config._projectRoot;
        const sourcePath = config.defaultSourcePath || 'force-app/main/default';
        const aiEnabled = config.features?.ai;

        if (!aiEnabled) {
          print.error(
            'AI features are disabled. Enable them in .sfdt/config.json (features.ai: true).',
          );
          process.exitCode = 1;
          return;
        }

        if (!(await isClaudeAvailable())) {
          print.error(
            'Claude CLI is not installed or not in PATH.\n' +
              '  Install from: https://docs.anthropic.com/en/docs/claude-cli',
          );
          process.exitCode = 1;
          return;
        }

        print.header(`PR Description (${options.base}...${options.head}, ${options.format})`);

        const context = await collectDiffContext(projectRoot, sourcePath, options);

        if (!context.hasChanges) {
          print.warning(`No commits or metadata changes between ${options.base} and ${options.head}.`);
          return;
        }

        const prompt = buildPrompt(options.format, context);

        const response = await runAiPrompt(prompt, {
          allowedTools: ['Read', 'Grep'],
          cwd: projectRoot,
          aiEnabled: true,
          interactive: false,
        });

        if (!response || response.exitCode !== 0) {
          print.error('AI call failed or returned no output.');
          process.exitCode = 1;
          return;
        }

        const output = (response.stdout || '').trim();
        if (!output) {
          print.error('AI returned empty output.');
          process.exitCode = 1;
          return;
        }

        if (options.output) {
          const absolute = path.isAbsolute(options.output)
            ? options.output
            : path.join(projectRoot, options.output);
          await fs.ensureDir(path.dirname(absolute));
          await fs.writeFile(absolute, output + '\n');
          print.success(`Wrote ${options.format} description → ${path.relative(projectRoot, absolute)}`);
        } else {
          console.log('');
          console.log(output);
          console.log('');
        }
      } catch (err) {
        print.error(`PR description generation failed: ${err.message}`);
        process.exitCode = 1;
      }
    });
}

/**
 * Gather the raw inputs the AI will summarize: commit messages, file list,
 * and a structured metadata component breakdown.
 */
async function collectDiffContext(cwd, sourcePath, options) {
  const execOpts = { cwd, reject: false };

  // Commit log
  const commitLimit = Math.max(1, parseInt(options.commitLimit, 10) || 30);
  const log = await execa(
    'git',
    ['log', '--pretty=format:%h %s', `-n`, String(commitLimit), `${options.base}..${options.head}`],
    execOpts,
  );

  // Name-status diff scoped to the source root (force-app/, etc.)
  const diff = await execa(
    'git',
    [
      'diff',
      '--name-status',
      options.base,
      options.head,
      '--',
      `${sourcePath.split('/')[0]}/`,
    ],
    execOpts,
  );

  const commits = (log.stdout || '').split('\n').filter(Boolean);
  const metadata = parseDiffToMetadata(diff.stdout || '', { sourcePath });

  const addCount = countMembers(metadata.additive);
  const delCount = countMembers(metadata.destructive);
  const hasChanges = commits.length > 0 || addCount > 0 || delCount > 0;

  return { commits, metadata, addCount, delCount, hasChanges };
}

function buildPrompt(format, context) {
  const basePrompt = format === 'slack' ? SLACK_PROMPT : GITHUB_PROMPT;
  const componentSection = formatMetadataForPrompt(context.metadata);
  const commitSection = context.commits.length
    ? context.commits.map((c) => `- ${c}`).join('\n')
    : '(no commits — working tree diff only)';

  return `${basePrompt}
--- COMMIT LOG (most recent first) ---
${commitSection}

--- METADATA CHANGES (${context.addCount} additive, ${context.delCount} destructive) ---
${componentSection}
`;
}

function formatMetadataForPrompt(metadata) {
  const lines = [];

  if (Object.keys(metadata.additive).length > 0) {
    lines.push('Additive:');
    for (const [type, members] of Object.entries(metadata.additive)) {
      const preview = members.slice(0, 10).join(', ');
      const suffix = members.length > 10 ? `, ...${members.length - 10} more` : '';
      lines.push(`  - ${type} (${members.length}): ${preview}${suffix}`);
    }
  }

  if (Object.keys(metadata.destructive).length > 0) {
    lines.push('Destructive:');
    for (const [type, members] of Object.entries(metadata.destructive)) {
      const preview = members.slice(0, 10).join(', ');
      const suffix = members.length > 10 ? `, ...${members.length - 10} more` : '';
      lines.push(`  - ${type} (${members.length}): ${preview}${suffix}`);
    }
  }

  if (lines.length === 0) {
    return '(no metadata changes detected in source directory)';
  }
  return lines.join('\n');
}
